version: '3.8'

services:
  web:
    build: .
    container_name: sinaloa-landing
    ports:
      - "8080:80"
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: sinaloa-jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: sinaloa-postgres
    environment:
      POSTGRES_DB: sinaloa_db
      POSTGRES_USER: sinaloa_user
      POSTGRES_PASSWORD: sinaloa_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  jenkins_home:
  postgres_data: